import type { AbilityDefinition } from '../contracts/abilities';
import { scaledDamage } from '../config/combat';
import { BLOSSOM_SPIRIT } from './summons';
import { INK_MEMORY } from './passives';
import { MASKS_BALANCE as M } from '../config/masks';

// Prototype balance, independent from reference-project character skills.
export const PROTOTYPE_ABILITIES: AbilityDefinition[] = [
 {id:'masks-shift',name:'เปลี่ยนหน้าพลิกวิญญาณ',shortName:'เปลี่ยนหน้า',range:5,castTicks:8,cooldownTicks:108,
 description:`วน พิโรธ → โศก → ยิ้ม · พิโรธพุ่งชก ${scaledDamage(M.wrathDamage)} HP แล้วผลัก ช่วง ${M.wrathBraceTicks/60} วินาทีหลังออกท่าลดดาเมจประชิดและการชน ${M.wrathBraceReduction*100}% ไม่ลดกระสุน พื้นที่ หรือสถานะ · โศกยิงปราณสามสาย ${scaledDamage(M.sorrowDamage)} HP ต่อเป้าหมาย ไม่ซ้อนดาเมจจากชุดเดียว และช้า 15% 2 วินาที · ยิ้มรอศัตรูเข้าใกล้ก่อนเปิดรับหนึ่งครั้ง ลดดาเมจ ${M.smileReduction*100}% แล้วคลื่นสวน ${scaledDamage(M.smileDamage)} HP ช่วงรับ 1.5 วินาที ช่วงรอไม่ป้องกัน · เปลี่ยนใบเมื่อออกท่าจริง ยิ้มเปลี่ยนเมื่อจบรับ · พร้อมทุก 1.8 วินาที`,
 effect:{kind:'masks-shift',damage:M.wrathDamage},basicCharge:{name:'เปลี่ยนหน้า',mode:'recharge',maxStacks:1,intervalTicks:108,damagePerStack:0}},
 {id:'masks-awaken',name:'สามวิญญาณตื่นรู้',shortName:'ตื่นรู้',range:5,castTicks:1,cooldownTicks:60,
 description:`ออกท่าปกติจริง 6 ครั้งเพื่อปลุกสามหน้ากาก · บัพอยู่จนใช้ครบทุกใบ เริ่มจากใบปัจจุบัน · พิโรธชก ${scaledDamage(M.wrathAwakenedDamage)} HP ไกลและผลักแรง ลดดาเมจประชิดและการชน ${M.wrathBraceReduction*100}% ช่วง ${M.wrathBraceTicks/60} วินาทีหลังออกท่า ติดรอยพิโรธ 3 วินาที ชนกำแพงระเบิดเพิ่ม 4.56 HP ครั้งเดียว · โศกยิงทะลุ ${scaledDamage(M.sorrowAwakenedDamage)} HP ช้า 25% และลดพลังโจมตี 20% 3 วินาที · ยิ้มรอศัตรูเข้าใกล้ ลดดาเมจ ${M.smileAwakenedReduction*100}% ได้สองครั้ง คลื่นสวน ${scaledDamage(M.smileAwakenedDamage)} HP ทุกครั้ง ถ้าหมดเวลาแล้วยังเหลือสิทธิ์ปล่อยคลื่นปิดท้ายหนึ่งครั้ง · ไม่สะสมอัลติขณะบัพ ไม่เสียใบถ้าถูกขัดก่อนออกท่า`,
 effect:{kind:'masks-awaken',damage:0},ultimate:{maxCharge:6,windupTicks:1,armedTicks:1,counterLabel:'เปลี่ยนหน้า',rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'เปลี่ยนหน้า'}},
 {id:'gates-strike',name:'หมัดเปิดด่าน',shortName:'เปิดด่าน',range:3,castTicks:1,cooldownTicks:84,
 description:'พุ่งเข้าชกระยะสั้นทุก 1.4 วินาที ทำ 4.56 HP และแรงขึ้น 8% ต่อประตู · ต่อยโดนและลด HP จริงเปิด 1 ประตู สูงสุด 8 · ระยะพุ่งเพิ่มตามขั้น · ตั้งแต่ 5 ประตูใช้วิชาเสีย 1 HP ที่ 7–8 เสีย 2 HP ไม่ทำให้ตัวเองตาย',
 effect:{kind:'gates-punch',damage:12},basicCharge:{name:'เปิดด่าน',mode:'recharge',maxStacks:1,intervalTicks:84,damagePerStack:0}},
 {id:'gates-unleash',name:'แปดประตูสะท้านฟ้า',shortName:'แปดประตู',range:3,castTicks:1,cooldownTicks:150,
 description:'กดใช้ได้ตั้งแต่ 1 ประตู โหมดอัตโนมัติรอครบ 8 · ใช้ประตูทั้งหมดพุ่งเข้าประชิดก่อนเริ่มชุดหมัด จำนวนหมัดเท่ากับประตู +2 · หมัดละ 1.9 HP หมัดสุดท้าย 5.7 HP พร้อมผลัก · ทุกหมัดตรวจระยะจริง หลบหนีหรือผนึกเพื่อหยุดชุดได้ · เปิดประตูใหม่หลังจบชุด',
 effect:{kind:'gates-combo',damage:5},ultimate:{maxCharge:8,windupTicks:1,armedTicks:24,counterLabel:'ประตู',rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'ประตู'}},
 {id:'automaton-command',name:'หุ่นกลพิทักษ์วิถี',shortName:'สั่งหุ่นกล',range:5,castTicks:8,cooldownTicks:126,
 description:'ทุก 2.1 วินาที สร้างป้อมหุ่นกล 24 HP ณ จุดร่ายหากยังไม่มี หรือสั่งหุ่นเดิมยิงลูกดอก 3 นัด นัดละ 1.9 HP · มีได้หนึ่งตัว ไม่ย้ายหรือฟื้นเลือดเมื่อสั่งซ้ำ · หุ่นรับดาเมจจากวิชาและการชนของศัตรูได้',
 effect:{kind:'automaton-command',damage:5,maxHP:24,speed:660,refillRadius:96},basicCharge:{name:'สั่งหุ่นกล',mode:'recharge',maxStacks:1,intervalTicks:126,damagePerStack:0}},
 {id:'automaton-awaken',name:'เทพจักรกลออกศึก',shortName:'เทพจักรกล',range:5,castTicks:1,cooldownTicks:60,
 description:'สั่งหุ่น 5 ครั้งจึงพร้อม · หุ่นแปลงเป็นนักรบไล่เข้าประชิด 5 วินาที กวาดแขนทำ 5.32 HP ต่อเป้าหมายหนึ่งครั้งต่อการกวาด · มีจังหวะเตือนก่อนฟัน · ใช้ HP เดิม หากไม่มีหุ่นจะสร้างใหม่ · จบแล้วกลับเป็นป้อม ณ จุดสุดท้าย · หลับหรือถูกผนึกยุติร่างนักรบ',
 effect:{kind:'automaton-awaken',damage:14,durationTicks:300,speed:480,radius:105,intervalTicks:48},ultimate:{maxCharge:5,windupTicks:18,armedTicks:120,counterLabel:'กลไก',rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'กลไก'}},
 {id:'retrace-follow',name:'กระบี่ตามเงา',shortName:'กระบี่เงา',range:5,castTicks:8,cooldownTicks:126,
 description:'ฝากกระบี่ไว้ที่จุดร่าย แล้วตามเส้นทางที่ตัวเองเดินผ่านใน 2 วินาทีถัดไป ช้ากว่าตัวจริง 1.2 วินาที เพื่อเว้นช่วงโจมตีด้านหลัง · ทำ 13.68 HP ต่อเป้าหมายหนึ่งครั้งต่อเล่ม · พร้อมทุก 2.1 วินาที · กระบี่ตามรอยจริง ไม่เล็งไล่ศัตรู',
 effect:{kind:'retrace-follow',damage:36,delayTicks:72,recordTicks:120,radius:22},basicCharge:{name:'กระบี่เงา',mode:'recharge',maxStacks:1,intervalTicks:126,damagePerStack:0}},
 {id:'retrace-return',name:'หนึ่งวิถีพันรอยกระบี่',shortName:'กระบี่ย้อน',range:5,castTicks:1,cooldownTicks:60,
 description:'ฝากกระบี่ 4 ครั้งจึงพร้อม · เผยเส้นทางย้อนหลัง 3 วินาที เตือน 0.4 วินาที แล้วปล่อยกระบี่ 3 เล่มห่างกัน 0.23 วินาที ย้อนรอยเร็วสองเท่า · เล่มละ 9.12 HP ต่อเป้าหมายหนึ่งครั้ง · ตัวเองยังเคลื่อนที่ได้ · หลับหรือถูกผนึกทำให้กระบี่สลาย',
 effect:{kind:'retrace-return',damage:24,historyTicks:180,warningTicks:24,intervalTicks:14,durationTicks:142,radius:26},ultimate:{maxCharge:4,windupTicks:12,armedTicks:120,counterLabel:'รอยกระบี่',rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'รอยกระบี่'}},
 {id:'thorn-plant',name:'บุปผาฝังผนัง',shortName:'ดอกหนาม',range:5,castTicks:8,cooldownTicks:126,
 description:'ทุก 2.1 วินาที วางดอกหนามบนกำแพงตามวิถีเด้งของศัตรู เตือน 0.5 วินาทีก่อนพร้อม · ชนกำแพงในช่วงหนามกว้าง 140 จึงโดน 11.4 HP แล้วดอกสลาย · เก็บได้ 4 ดอก นาน 20 วินาที · บอลชนและดอกระหว่างเดินทางไม่ทำดาเมจ',
 effect:{kind:'thorn-plant',damage:30,halfWidth:70,armTicks:30,lifetimeTicks:1200},basicCharge:{name:'ดอกหนาม',mode:'recharge',maxStacks:1,intervalTicks:126,damagePerStack:0}},
 {id:'thorn-garden',name:'เรือนบุปผาปิดทาง',shortName:'เรือนหนาม',range:5,castTicks:1,cooldownTicks:60,
 description:'วางดอก 4 ครั้งจึงพร้อม · ขยายหนามแต่ละดอกตามกำแพงเป็นช่วงกว้าง 280 นาน 6 วินาที โดนครั้งละ 6.84 HP และดอกไม่สลาย · เป้าหมายเดิมโดนหนามของผู้ใช้คนเดียวกันซ้ำได้ทุก 0.8 วินาที · หากไม่มีดอกจะวางให้ 2 จุดพร้อมช่วงเตือน · กลางสนามปลอดภัย · หลับหรือถูกผนึกยุติอัลติ',
 effect:{kind:'thorn-garden',damage:18,halfWidth:140,durationTicks:360,cooldownTicks:48},ultimate:{maxCharge:4,windupTicks:24,armedTicks:120,counterLabel:'บุปผา',rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'บุปผา'}},
 {id:'wind-fan',name:'พัดเฉือนข้าง',range:3,castTicks:8,cooldownTicks:126,
 description:'กวาดลมรูปพัดในระยะกลาง ทำ 7.6 HP แล้วผลักศัตรูออกด้านข้างของแนวฟัน · แต่ละเป้าหมายโดนได้ครั้งเดียวต่อพัด · ผนังและแท่นบังลมได้ · พร้อมใช้ทุก 2.1 วินาที',
 effect:{kind:'wind-fan',damage:20,radius:205,arcDegrees:100,activeTicks:10,push:480},basicCharge:{name:'สายลม',mode:'recharge',maxStacks:1,intervalTicks:126,damagePerStack:0}},
 {id:'wind-monsoon',name:'เนตรมรสุม',range:5,castTicks:1,cooldownTicks:60,
 description:'ใช้พัด 4 ครั้ง · วางพายุกลางสนาม 4 วินาที เบนทิศเคลื่อนที่ของทุกคนรวมผู้ร่าย และเบนกระสุนที่บินผ่านตามเข็มนาฬิกาโดยไม่เร่งความเร็ว · วงลมรัศมี 95–174 ทำ 2.66 HP ทุก 0.6 วินาทีแก่ศัตรู · ตาพายุปลอดภัยจากลมและดาเมจพายุ · ไม่เบนลำแสงหรือวิชาที่วางประจำจุด · ถูกผนึกหรือหลับจะสลาย',
 effect:{kind:'wind-storm',damage:7,radius:174,eyeRadius:95,durationTicks:240,intervalTicks:36,turnRate:2.4},ultimate:{maxCharge:4,windupTicks:18,armedTicks:120,counterLabel:'กระแสลม',rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'กระแสลม'}},
 {id:'cannon-round',name:'กระสุนครามสะเทือนฟ้า',range:5,castTicks:8,cooldownTicks:150,
 description:'ยิงกระสุนเพลิงครามเล็งนำทุก 2.5 วินาที ทำ 5.7 HP และระเบิดวงเล็กเมื่อปะทะ · แรงถีบผลักตัวเองสวนทางยิง · เป้าหมายหนึ่งตัวรับดาเมจจากนัดเดียวได้ครั้งเดียว',
 effect:{kind:'cannon-shot',damage:15,speed:750,blastRadius:64,recoil:620},basicCharge:{name:'กระสุน',mode:'recharge',maxStacks:1,intervalTicks:150,damagePerStack:0}},
 {id:'cannon-salvo',name:'สามนัดทลายนภา',range:5,castTicks:1,cooldownTicks:60,
 description:'ยิงสามนัดห่างกัน 0.5 วินาที เล็งใหม่และถีบตัวทุกนัด · นัดละ 4.56 HP สองนัดแรกระเบิดวงเล็ก นัดสุดท้ายเจาะศัตรูถึงกำแพงแล้วระเบิด 6.84 HP ในวงใหญ่ · ไม่ทบดาเมจกระสุนกับระเบิดใส่เป้าหมายเดิม · หลับหรือถูกผนึกจะหยุดนัดที่ยังไม่ยิง',
 effect:{kind:'cannon-salvo',damage:12,speed:800,blastRadius:64,recoil:700,intervalTicks:30,finalDamage:18,finalRadius:110},ultimate:{maxCharge:4,windupTicks:12,armedTicks:120,counterLabel:'เพลิงคราม',rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'เพลิงคราม'}},
 {id:'crystal-lance',name:'ผลึกแยกประกาย',range:5,castTicks:8,cooldownTicks:126,
 description:'ทุก 2.1 วินาที ยิงหอกทะลุศัตรู ทำ 6.84 HP แล้วปักกำแพง เก็บผลึกได้ 2 จุด · เมื่อมีผลึก สลับยิงตรงกับส่งผ่านผลึกที่มีทางเปิด แตกเป็นพัด 3 แฉก แฉกละ 5.13 HP · หนึ่งชุดโดนแต่ละเป้าหมายได้ครั้งเดียว กำแพงและแท่นหยุดเศษผลึกได้',
 effect:{kind:'crystal-lance',damage:18,speed:740,splitMultiplier:.75},basicCharge:{name:'ประกาย',mode:'recharge',maxStacks:1,intervalTicks:126,damagePerStack:0}},
 {id:'crystal-heaven',name:'เจ็ดเหลี่ยมผนึกฟ้า',range:5,castTicks:1,cooldownTicks:60,
 description:'ใช้สกิลปกติ 4 ครั้ง · สร้างวงผลึก 7 จุดรัศมี 140 รอบตำแหน่งศัตรู คงจุดเดิมและไม่กักการเคลื่อนที่ · เตือน 0.3 วินาที แล้วลำแสงชิ่งตัดวง 7 แนว เว้น 0.3 วินาที แนวละ 2.28 HP · สุดท้ายยิงเศษเข้าศูนย์กลาง ทำ 5.32 HP ต่อเป้าหมายได้ครั้งเดียว แท่นบังได้และถูกผนึกวิชาแล้วหยุดค่ายกล',
 effect:{kind:'crystal-array',damage:14,lineDamage:6,radius:140,intervalTicks:18,lineWidth:14},ultimate:{maxCharge:4,windupTicks:12,armedTicks:120,counterLabel:'เหลี่ยมฟ้า',rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'เหลี่ยมฟ้า'}},
 {id:'dream-butterfly',name:'ผีเสื้อฝากฝัน',range:4,castTicks:8,cooldownTicks:120,
 description:'ยิงผีเสื้อเล็งนำทุก 2 วินาที ทำ 5.7 HP · โดนจริงสะสมง่วงงุน 6 วินาที ครบ 3 ชั้นหลับจนกว่าจะเสีย HP จริง หยุดเคลื่อนที่และใช้วิชา · ดาเมจปลุกทันที แล้วต้านการหลับ 2.5 วินาที',
 effect:{kind:'projectile',damage:15,speed:720,radius:16,lifetimeTicks:75,aiming:'predictive',maxLeadSeconds:.22},
 onHitStatus:{id:'dream-drowsy',name:'ง่วงงุน',durationTicks:360,stacking:'stack',maxStacks:3,sourceScoped:true,effect:{kind:'drowsy',immunityTicks:150,ultimateId:'dream-night',bonusMultiplier:1.6},vfxColor:'#d5b9ff'},
 basicCharge:{name:'ปีกฝัน',mode:'recharge',maxStacks:1,intervalTicks:120,damagePerStack:0}},
 {id:'dream-night',name:'ราตรีพันฝัน',range:5,castTicks:1,cooldownTicks:60,
 description:'ยิงปกติครบ 4 ครั้ง · กางคลื่นปีกจากจุดที่ยืน รัศมี 300 ใน 0.6 วินาที ทำให้หลับจนกว่าจะเสีย HP จริง แล้วส่งผีเสื้อใหญ่ตามหลัง 0.3 วินาที · ทำ 8.36 HP หรือ 13.38 HP หากเป้าหมายยังหลับจากตน · ตื่นก่อนยังถูกไล่ล่าแต่ไม่มีโบนัส แท่นบังคลื่นและผีเสื้อได้',
 effect:{kind:'dream-wave',damage:22,radius:300,growthTicks:36,delayTicks:18,speed:600},
 ultimate:{maxCharge:4,windupTicks:12,armedTicks:120,counterLabel:'ปีกฝัน',rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'ปีกฝัน'}},
 {id:'feather-silver',name:'ขนเงินฝากนภา',range:5,castTicks:8,cooldownTicks:126,description:`ทุก 2.1 วินาที ยิงขนนกทะลุศัตรู ทำ ${scaledDamage(18)} HP ต่อเป้าหมายได้ครั้งเดียว แล้วปักกำแพง · เก็บสูงสุด 5 เล่ม เล่มเก่าหายเมื่อเกิน · ถ้าชนแท่นหรือถูกดูดจะไม่ปักขน`,effect:{kind:'feather-shot',damage:18,speed:700},basicCharge:{name:'ขนเงิน',mode:'recharge',maxStacks:1,intervalTicks:126,damagePerStack:0}},
 {id:'feather-home',name:'พันปีกคืนรัง',range:5,castTicks:1,cooldownTicks:60,description:`ใช้ขนเงินฝากนภา 4 ครั้ง · เรียกขนนกที่ปักกลับทีละเล่ม เว้น 0.3 วินาที ทำ ${scaledDamage(22)} HP ต่อเล่มต่อเป้าหมาย · แต่ละเล่มบินตรงเข้าจุดที่ผู้ใช้อยู่ตอนเริ่มคืน แล้วสลาย ไม่ไล่ตามต่อ · ถ้าไม่มีขนปัก สร้าง 3 เล่มรอบสนามก่อนเรียกกลับ · แท่นหยกขวางได้`,effect:{kind:'feather-recall',damage:22,speed:750,intervalTicks:18},ultimate:{maxCharge:4,windupTicks:12,armedTicks:120,counterLabel:'ปีกเงิน',rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'ปีกเงิน'}},
 {id:'lantern-ward',name:'โคมรับเคราะห์',range:5,castTicks:6,cooldownTicks:138,
  description:`ตั้งโคมด้านหน้า 0.8 วินาที ทุก 2.3 วินาที · รับกระสุนปราณ 1 ลูก หรือลดดาเมจประชิด/ชน 1 ครั้ง 30% ใช้สิทธิ์ร่วมกัน · รับสำเร็จได้เชื้อวิญญาณ 1/3 แล้วพุ่งสวน ${scaledDamage(17.55)} HP · ถ้าไม่ถูกโจมตีจะพุ่งเอง ${scaledDamage(13)} HP เมื่อครบเวลา`,
  effect:{kind:'lantern',damage:13,receiveTicks:48,reduction:.3,counterMultiplier:1.35},basicCharge:{name:'โคม',mode:'recharge',maxStacks:1,intervalTicks:138,damagePerStack:0}},
 {id:'lantern-souls',name:'ร้อยวิญญาณออกโคม',range:5,castTicks:1,cooldownTicks:60,
  description:`โคมพุ่งโดนจริงครบ 3 ครั้ง · เปิดโคมปล่อยภูตพื้นฐาน 3 ตน เพิ่มตามเชื้อวิญญาณสูงสุด 6 ตน แล้วใช้เชื้อทั้งหมด · ตนละ ${scaledDamage(9)} HP เว้น 0.3 วินาที · เลี้ยวหาเป้าเฉพาะ 0.3 วินาทีแรก จากนั้นบินตรง โดนแล้วสลาย และกำแพงหรือแท่นหยุดภูตได้ · ใช้ได้แม้ไม่มีเชื้อ`,
  effect:{kind:'soul-release',damage:9,intervalTicks:18,speed:560,guideTicks:18,lifetimeTicks:90},ultimate:{maxCharge:3,windupTicks:12,armedTicks:120,counterLabel:'แสงโคม',rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'แสงโคม'}},
 {id:'time-sand',name:'ทรายกลืนกาล',range:4,castTicks:8,cooldownTicks:120,
  description:`ยิงคมทรายทุก 2 วินาที ทำ ${scaledDamage(14)} HP และฝากรอยกาล 2 วินาที · บันทึกดาเมจที่ศัตรูได้รับจริงหลังติดตรา เมื่อครบเวลาสร้างดาเมจเพิ่ม 35% ของที่บันทึก สูงสุด 8 HP ก่อนการป้องกัน · ไม่ทบตราหรือบันทึกดาเมจจากรอยกาลซ้ำ`,
  effect:{kind:'projectile',damage:14,speed:780,radius:13,lifetimeTicks:85,aiming:'predictive',maxLeadSeconds:.22,timeMark:{durationTicks:120,ratio:.35,cap:8}},
  basicCharge:{name:'เม็ดทราย',mode:'recharge',maxStacks:1,intervalTicks:120,damagePerStack:0}},
 {id:'time-return',name:'หวนคืนหนึ่งลมหายใจ',range:5,castTicks:1,cooldownTicks:60,
  description:`คมทรายโดนจริงครบ 4 ครั้ง · วางนาฬิกาหยกแล้วต่อสู้อีก 3 วินาที จากนั้นย้อนกลับจุดเดิมหรือพื้นที่ว่างใกล้เคียง คืน 35% ของ HP ที่เสียระหว่างนั้น สูงสุด 10 HP และไม่เกิน HP ตอนเริ่ม · ระเบิดทรายรัศมี 155 ทำ ${scaledDamage(28)} HP · ระหว่างรอย้อนยังตายได้ ไม่ล้างสถานะ และถูกผนึกวิชาจะยกเลิก`,
  effect:{kind:'time-rewind',damage:28,durationTicks:180,radius:155,healRatio:.35,healCap:10},
  ultimate:{maxCharge:4,windupTicks:12,armedTicks:120,counterLabel:'ทรายกาล',rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'ทรายกาล'}},
 {id:'portal-step',name:'ก้าวข้ามสุญญะ',range:5,castTicks:8,cooldownTicks:132,
 description:'ทุก 2.2 วินาที เปิดประตูด้านหน้าเชื่อมจุดข้างศัตรู 1.5 วินาที · วิ่งเข้าใช้ได้ครั้งเดียว ออกแล้วพุ่งพร้อมคมมิติ 7.6 HP · คมมิติโดนจริงจึงสะสมอัลติ จุดออกต้องว่าง',
 effect:{kind:'portal',damage:20,durationTicks:90,bodyUses:1,projectileUses:0,shots:0}},
 {id:'portal-fold',name:'พับฟ้าสลับทิศ',range:5,castTicks:1,cooldownTicks:84,
 description:'คมมิติโดน 3 ครั้ง · เปิดประตูคู่บนกำแพง 5 วินาที ตัวเองผ่านได้ 3 ครั้ง เว้น 0.8 วินาที ออกแล้วระเบิดมิติใกล้ตัว 2.28 HP · ส่งคมมิติ 4 ลูก ลูกละ 4.56 HP เข้าประตูแล้วเล็งออกหาศัตรู กระสุนตนผ่านได้รวม 6 ครั้งและไม่เพิ่มดาเมจ · ใช้สกิลปกติร่วมได้ ไม่สะสมอัลติระหว่างเปิดประตู',
 effect:{kind:'portal',damage:12,durationTicks:300,bodyUses:3,projectileUses:6,shots:4},
 ultimate:{maxCharge:3,windupTicks:18,armedTicks:120,counterLabel:'รอยแยก',rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'รอยแยก'}},
 {id:'thread-needle',name:'เข็มเย็บชะตา',range:4,castTicks:9,cooldownTicks:120,
  description:`ยิงเข็มทุก 2 วินาที สร้าง ${scaledDamage(12)} HP · โดนจริงฝากด้าย 4 วินาที เมื่อศัตรูชิ่งกำแพงครั้งถัดไป ด้ายขาดสร้างเพิ่ม ${scaledDamage(8)} HP หนึ่งครั้ง · ฝากซ้ำต่อเวลา ไม่ทบชั้น · เข็มโดนจึงสะสมอัลติ`,
  basicCharge:{name:'เข็มชะตา',mode:'recharge',maxStacks:1,intervalTicks:120,damagePerStack:0},
  effect:{kind:'projectile',damage:12,speed:740,radius:12,lifetimeTicks:80,aiming:'predictive',maxLeadSeconds:.25,fateThread:{mode:'mark',durationTicks:240,bonusDamage:8}}},
 {id:'thread-fate',name:'พันด้ายเย็บชะตา',range:5,castTicks:1,cooldownTicks:60,
  description:`เข็มโดนจริงครบ 3 ครั้ง · ง้าง 0.25 วินาทีแล้วยิงด้าย ${scaledDamage(8)} HP ผูกศัตรูกับกำแพง 4 วินาที · ด้ายหดดึงกลับเอง เริ่มหลัง 0.5 วินาที แล้วกระตุกทุก 0.8 วินาที สร้าง ${scaledDamage(7.2)} HP สูงสุด 5 ครั้ง · ถ้ามีด้ายปกติอยู่จะใช้ด้ายนั้นเสริมครั้งสุดท้าย ${scaledDamage(4)} HP · ยังเคลื่อนที่และใช้สกิลได้ ยิงหลบได้ แท่นขวางหรือผู้ใช้ถูกผนึกวิชาแล้วด้ายขาด ไม่สะสมอัลติขณะผูก`,
  effect:{kind:'projectile',damage:8,speed:800,radius:19,lifetimeTicks:80,aiming:'predictive',maxLeadSeconds:.2,fateThread:{mode:'tether',durationTicks:240,bonusDamage:4,jerkDamage:7.2,maxJerks:5,jerkIntervalTicks:48,strength:720,slack:50}},
  ultimate:{maxCharge:3,windupTicks:15,armedTicks:120,counterLabel:'ปมชะตา',rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'ปมชะตา'}},
 {id:'scribe-glyph',name:'อักษรทะลวงปราณ',range:4,castTicks:10,cooldownTicks:144,
 description:'ปล่อยอักขระ 3 สายเป็นพัดแคบ เล็งนำศัตรู · ทำ 6.08 HP ต่อเป้าหมายได้ครั้งเดียวต่อชุด ฟื้นทุก 2.4 วินาที และสะสมเปิดคัมภีร์ 1 ครั้งต่อชุดที่โดนจริง · กำแพงและแท่นบังได้',
 effect:{kind:'projectile',damage:16,speed:680,radius:13,lifetimeTicks:60,aiming:'predictive',maxLeadSeconds:.22,volley:{count:3,spreadDegrees:12}}},
 {id:'scribe-return',name:'คืนวิชาสู่เจ้าของ',range:4,castTicks:24,cooldownTicks:150,
 description:'อักขระปกติโดนจริง 3 ชุด · เปิดคัมภีร์ 0.4 วินาที ใช้บันทึกล่าสุดคืนวิชา: กระสุน/ภูตอักขระ 3 นัด คลื่นประชิด 2 จังหวะ ค่ายกล 1 ครั้ง หรือลำแสง 1 ครั้ง · ดาเมจรวมสูงสุด 18.24 HP ต่อเป้าหมายก่อนหลบ · คัมภีร์ว่างใช้ลำแสงอักขระ ไม่คืนเลือดหรือคัดลอกอัลติ',
 effect:{kind:'script-return',damage:48},ultimate:{maxCharge:3,rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}],windupTicks:24,armedTicks:120,counterLabel:'เปิดคัมภีร์'},ultimatePresentation:{kind:'count',label:'เปิดคัมภีร์'}},
 {id:'fox-flame',name:'เสน่ห์ลวงใจ',range:4,castTicks:8,cooldownTicks:145,
 description:'ยิงเพลิงจิ้งจอกเล็งนำ ทำ 6.08 HP · ติดหลงเสน่ห์ 2 วินาที เบนทิศเข้าหาผู้ใช้ใน 0.6 วินาทีแรก · ศัตรูยังเคลื่อนที่และใช้สกิลได้ กำแพงและแท่นบังเพลิงได้',
 effect:{kind:'projectile',damage:16,speed:690,radius:16,lifetimeTicks:60,aiming:'predictive',maxLeadSeconds:.25}},
 {id:'fox-ninefold',name:'เก้าหางล่าจันทร์',range:4,castTicks:12,cooldownTicks:180,
 description:'เพลิงปกติโดน 3 ครั้ง · แผ่เก้าหางก่อนพุ่งล่า 3 จังหวะ เล็งใหม่ทุกครั้ง ทำ 3.42 / 3.42 / 5.13 HP และทิ้งเพลิงระเบิดตามหลังครั้งละ 1.52 HP · จังหวะสุดท้ายแรงขึ้น 25% หากยังหลงเสน่ห์จากตน · ไม่เป็นอมตะและพุ่งผ่านแท่นไม่ได้',
 effect:{kind:'fox-hunt',damage:9,speed:1050,radius:30,dashTicks:20,pauseTicks:18,emberDamage:4,emberRadius:72,emberDelay:12,charmBonus:1.25},
 ultimate:{maxCharge:3,rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}],windupTicks:12,armedTicks:120,counterLabel:'เพลิงจิ้งจอก'},ultimatePresentation:{kind:'count',label:'เพลิงจิ้งจอก'}},
 {id:'bell-resound',name:'ระฆังสะเทือนปราณ',shortName:'กังวาน',range:3,castTicks:1,cooldownTicks:114,
  description:'ปล่อยคลื่นเสียงรอบตัว ทำ 7.6 HP ต่อเป้าหมายครั้งเดียว ฟื้นทุก 1.9 วินาที · รัศมี 160 เพิ่ม 22 ต่อกังวาน สูงสุด 226 ใช้กังวานทั้งหมดเมื่อปล่อย · คลื่นขยายใน 0.5 วินาที หลบออกจากขอบคลื่นหรือใช้แท่นบังได้',
  effect:{kind:'bell',damage:20,radius:160,growthTicks:30,pulses:1,intervalTicks:30,reduction:1,guardTicks:0,bonusRadiusPerStack:22}},
 {id:'bell-judgment',name:'มหาระฆังพิพากษา',range:4,castTicks:18,cooldownTicks:120,
  description:'คลื่นปกติโดนจริง 3 ครั้ง · วางระฆังกลางสนาม ลดดาเมจที่รับ 35% นาน 1.5 วินาที ปล่อยคลื่น 3 จังหวะห่างกัน 0.5 วินาที รัศมี 240 · สองจังหวะแรกทำครั้งละ 6.84 HP จังหวะสุดท้าย 10.26 HP และผลักออก · คลื่นผ่านผู้ใช้เพิ่มกังวาน 1 ต่อคลื่น สูงสุด 3 · ยังเคลื่อนที่และถูกโจมตีได้',
  effect:{kind:'bell',damage:18,radius:240,growthTicks:30,pulses:3,intervalTicks:30,reduction:.65,guardTicks:90,bonusRadiusPerStack:0},
  ultimate:{maxCharge:3,rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}],windupTicks:18,armedTicks:120,counterLabel:'เสียงระฆัง'},ultimatePresentation:{kind:'count',label:'เสียงระฆัง'}},
 {id:'beam-finger',name:'ดัชนีแสงทะลวง',range:5,castTicks:33,cooldownTicks:120,
 description:'หยุดกายชาร์จ 0.55 วินาที เล็งตามศัตรูและล็อกแนวช่วงท้าย 0.1 วินาที · ปล่อยลำแสงกว้าง 14 พุ่งถึงกำแพง ทำ 7.6 HP ต่อเป้าหมายครั้งเดียว ก่อนคืนการเคลื่อนที่ใน 0.2 วินาที · รับดาเมจระหว่างชาร์จยกเลิกทันทีและเสียชาร์จ · ยิงทะลุตัวละครได้แต่แท่นบัง ฟื้นทุก 2 วินาที',
 effect:{kind:'beam',damage:20,width:14,chargeTicks:33,recoveryTicks:12,aimLockTicks:6},basicCharge:{name:'ปราณดัชนี',mode:'recharge',maxStacks:1,intervalTicks:120,damagePerStack:0}},
 {id:'beam-void',name:'หนึ่งดัชนีดับสุญญะ',range:5,castTicks:1,cooldownTicks:60,
 description:'ยิงดัชนีปกติโดนจริงครบ 3 ครั้ง · หยุดกายชาร์จ 0.75 วินาที ล็อกแนวช่วงท้าย 0.15 วินาที ก่อนปล่อยลำแสงมหาสุญญะกว้าง 64 ถึงกำแพง ทำ 22.04 HP ต่อเป้าหมายครั้งเดียว · คืนการเคลื่อนที่หลังยิง 0.3 วินาที · รับดาเมจระหว่างชาร์จท่าล้มเหลวและเสียเจตดัชนีทั้งหมด ไม่มีอมตะและไม่ดูดเลือด',
 effect:{kind:'beam',damage:58,width:64,chargeTicks:45,recoveryTicks:18,aimLockTicks:9},ultimate:{maxCharge:3,windupTicks:1,armedTicks:120,counterLabel:'เจตดัชนี',rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'เจตดัชนี'}},
 {id:'go-placement',name:'หมากหนึ่งพลิกกระดาน',range:5,castTicks:9,cooldownTicks:108,
 description:`ยิงหมากดำ–ขาวสลับกันทุก 1.8 วินาที กระแทก ${scaledDamage(14)} HP แล้วปักพื้น 6 วินาที · คู่ล่าสุดเชื่อมแนวปราณ เตือน 0.3 วินาทีก่อนมีผล · วิ่งตัดเส้นรับ ${scaledDamage(12)} HP และแต้มเสียเปรียบ ต้องออกจากเส้นก่อนและเว้น 1 วินาทีจึงโดนซ้ำ · หมากและเส้นไม่ทะลุแท่น ไม่ขวางการเคลื่อนที่`,
 effect:{kind:'go-stone',damage:14,speed:620,lifetimeTicks:360,lineDamage:12,lineWidth:8,lineCooldownTicks:60},basicCharge:{name:'หมาก',mode:'recharge',maxStacks:1,intervalTicks:108,damagePerStack:0}},
 {id:'go-checkmate',name:'ปิดกระดานผนึกชะตา',range:5,castTicks:1,cooldownTicks:45,
 description:`วางหมากครบ 4 ครั้ง · รวมปราณ 0.3 วินาทีแล้วล้อมตำแหน่งศัตรูด้วยหกหมาก รัศมี 150 · เส้นพาดกระดานเปิดทีละแนว แนวละ ${scaledDamage(10)} HP ต่อเป้าหมายครั้งเดียว ก่อนระเบิดพื้นที่ ${scaledDamage(28)} HP · สลายแต้มเสียเปรียบเพิ่มแต้มละ ${scaledDamage(4)} HP สูงสุด 3 แต้ม · หนีออกจากกระดานได้ ไม่ดึง ไม่ผนึกการเคลื่อนที่ และหยุดวางหมากระหว่างอัลติ`,
 effect:{kind:'go-board',damage:28,radius:150,lineDamage:10,lineWidth:12,intervalTicks:24},ultimate:{maxCharge:4,windupTicks:18,armedTicks:120,counterLabel:'ตาเดิน',rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'ตาเดิน'}},
  {id:'scythe-cleave',name:'เคียวกวาดราตรี',range:3,castTicks:9,cooldownTicks:126,
    description:`ง้าง 0.15 วินาทีแล้วกวาดเคียวด้านหน้า 150 องศา ระยะ 180 ทำ ${scaledDamage(12)} HP · ช่วงปลายระยะ 32% แรงขึ้น 35% · แนวฟันมีผล 0.13 วินาที โดนแต่ละตัวได้ครั้งเดียวและฝากรอยจันทร์ · ฟื้นทุก 2.1 วินาที ฟันพลาดไม่สะสมอัลติ`,
    effect:{kind:'sweep',damage:12,radius:180,arcDegrees:150,activeTicks:8,tipStart:.68,tipMultiplier:1.35},
    basicCharge:{name:'คมจันทร์',mode:'recharge',maxStacks:1,intervalTicks:126,damagePerStack:0}},
  {id:'scythe-eclipse',name:'จันทร์ดับตัดชะตา',range:3,castTicks:1,cooldownTicks:45,
    description:`ฟันโดนจริงครบ 3 ครั้ง · ง้าง 0.2 วินาทีแล้วพุ่งผ่านตามแนวเล็ง 0.3 วินาที ก่อนฟันย้อนเป็นวงจันทร์รอบจุดหยุดรัศมี 140 ทำ ${scaledDamage(22)} HP · สลายรอยจันทร์ของตนเพิ่มตราละ ${scaledDamage(4)} HP สูงสุด 3 ตรา · เป้าหมายที่มีตราและ HP ไม่เกิน 35% รับเพิ่ม 25% สูงสุด ${scaledDamage(42.5)} HP · โดนแต่ละตัวได้ครั้งเดียว ไม่ฮีล ไม่อมตะ ไม่ล็อกเป้าหลังพุ่ง แท่นและกำแพงหยุดการพุ่งได้`,
    effect:{kind:'sweep',damage:22,radius:140,arcDegrees:360,activeTicks:9,tipStart:1,tipMultiplier:1,dash:{speed:900,durationTicks:18}},
    ultimate:{maxCharge:3,windupTicks:12,armedTicks:90,counterLabel:'เจตเคียว',rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}]},ultimatePresentation:{kind:'count',label:'เจตเคียว'}},
  {id:'umbrella-return',name:'ร่มเวียนบุปผา',range:4,castTicks:9,cooldownTicks:144,
    description:`ขว้างร่มโค้งออกไปแล้วบินกลับเข้ามือ ทำ ${scaledDamage(20)} HP ต่อขา ศัตรูแต่ละตัวโดนได้ครั้งเดียวขาไปและครั้งเดียวขากลับ · ฟื้นทุก 2.4 วินาที ระหว่างร่มลอยจะเสียการป้องกันและใช้วิชาอื่นไม่ได้ · กำแพงและแท่นขวางร่มได้`,
    basicCharge:{name:'ร่มบุปผา',mode:'recharge',maxStacks:1,intervalTicks:144,damagePerStack:0},
    effect:{kind:'returning-weapon',damage:20,reach:360,radius:32,outboundTicks:24,returnSpeed:900,lifetimeTicks:180,curve:35,heldReduction:.25}},
  {id:'umbrella-heaven',name:'พันร่มคืนสวรรค์',range:0,castTicks:0,cooldownTicks:30,
    description:`รับการโจมตีหรือขว้างร่มโดนสะสมวายุครบ 3/3 แล้วกางร่มปราณ 2 วินาที ลดดาเมจโดยตรง 50% · ครบเวลาสวนด้วยคลื่นวายุรอบตัวรัศมี 200 ทำ ${scaledDamage(30)} HP บวกแรงที่ป้องกันไว้ สูงสุด ${scaledDamage(60)} HP · ไม่ขว้างร่มหรือสะสมวายุระหว่างอัลติ ไม่ป้องกันพิษและไฟ ไม่กันสถานะควบคุม · ถูกผนึกวิชาจะสลายร่มและยกเลิกแรงสวน`,
    effect:{kind:'guard-burst',damage:30,durationTicks:120,reduction:.5,bonusCap:30,radius:200},
    ultimate:{maxCharge:3,windupTicks:12,armedTicks:90,counterLabel:'วายุ',rules:[{trigger:'passive-proc',amount:1,intervalTicks:45}]},
    ultimatePresentation:{kind:'count',label:'วายุ'}},
  {id:'archer-step',name:'ก้าวถอยสะบั้นดาว',range:5,castTicks:9,cooldownTicks:90,
    description:`ยิงศรดารา ${scaledDamage(8)} HP ทุก 1.5 วินาที เล็งเผื่อเส้นทางช่วงสั้น · เมื่อศัตรูอยู่ใกล้กว่า 190 จะถอยพร้อมยิงสวน เว้นการถอยอย่างน้อย 2.5 วินาที · ไม่อมตะและกำแพงยังขวางได้ · ยิงโดนจึงฝากตราดาวและสะสมอัลติ`,
    basicCharge:{name:'ศรดารา',mode:'recharge',maxStacks:1,intervalTicks:90,damagePerStack:0},
    effect:{kind:'projectile',damage:8,speed:760,radius:10,lifetimeTicks:100,aiming:'predictive',maxLeadSeconds:.3,retreat:{range:190,strength:660,cooldownTicks:150}}},
  {id:'archer-skyfall',name:'ศรเดียวดับนภา',range:5,castTicks:1,cooldownTicks:48,
    description:`ยิงปกติโดนจริงครบ 3 ครั้งจึงพร้อม · ปล่อยศรใหญ่ทันทีหลังประกาศท่า ไม่แสดงศรล่วงหน้า ${scaledDamage(24)} HP ทะลุผู้ประลอง แต่ละคนโดนได้ครั้งเดียว · ระเบิดตราดาวของตนเพิ่มตราละ ${scaledDamage(6)} HP สูงสุด ${scaledDamage(42)} HP ก่อนโบนัสจุดอ่อน · แนวยิงล็อก หลบได้ และติดกำแพงหรือแท่น`,
    effect:{kind:'projectile',damage:24,speed:1000,radius:19,lifetimeTicks:90,pierce:7,aiming:'predictive',maxLeadSeconds:.35},
    ultimate:{maxCharge:3,windupTicks:1,armedTicks:90,counterLabel:'เจตศร',rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}]},
    ultimatePresentation:{kind:'count',label:'เจตศร',statusCounter:{statusId:'star-quarry',maximum:3}}},
  {id:'drunken-sway',name:'ก้าวเมาหลบเงา',range:3,castTicks:6,cooldownTicks:132,
    description:`ตั้งท่า 0.1 วินาทีแล้วติด “เมาหลบคม” 0.5 วินาที หลบสกิลหรือสถานะใหม่ได้ 1 ครั้ง · ชนจริงหรือหลบสกิลสำเร็จจะเปิดหมัดสวน ${scaledDamage(22)} HP ตามหลัง 0.1 วินาที 1 หมัดต่อท่า · สวนศัตรูได้ในระยะ 240 และแท่นขวางได้ · ขณะตั้งท่าลดดาเมจชน 25% ฟื้นท่าทุก 2.2 วินาที หากไม่มีใครโจมตีจะไม่มีหมัดสวน`,
    selfStatus:{id:'drunken-skill-guard',name:'เมาหลบคม',durationTicks:30,stacking:'refresh',effect:{kind:'skill-evasion',once:true},vfxColor:'#f7dcb0'},
    basicCharge:{name:'ก้าวเมา',mode:'recharge',maxStacks:1,intervalTicks:132,damagePerStack:0},
    effect:{kind:'impact-form',damage:22,speedMultiplier:1.04,durationTicks:30,hits:1,pairCooldownTicks:60,defense:{collisionMultiplier:.75,knockbackMultiplier:1},formName:'โยกหลบ',rebound:{strength:270,delayTicks:6,radius:68,maxHitsPerTarget:1}}},
  {id:'drunken-heaven',name:'เมรัยพลิกสวรรค์',range:0,castTicks:0,cooldownTicks:30,
    description:`ฤทธิ์สุราครบ 4/4 จอก แปรกาย 2 วินาที ติด “เมาไร้เงา” เฉพาะ 0.7 วินาทีแรก หลบสกิลโจมตีทุกครั้งและกันสถานะใหม่ · ความเร็วเพิ่ม 12% ปะทะแล้วแฉลบพร้อมหมัดปราณ ${scaledDamage(19)} HP ตามหลัง 0.1 วินาที เป้าหมายละสูงสุด 2 หมัด ห่างกัน 0.75 วินาที · ยังรับดาเมจชนเต็ม 100% และพิษหรือไฟที่ติดอยู่ก่อน · ไม่สะสมจอกระหว่างอัลติ`,
    selfStatus:{id:'drunken-untouchable',name:'เมาไร้เงา',durationTicks:42,stacking:'refresh',effect:{kind:'skill-evasion',once:false},vfxColor:'#fff0bf'},
    effect:{kind:'impact-form',damage:19,speedMultiplier:1.12,durationTicks:120,hits:2,pairCooldownTicks:45,strikeCooldownTicks:30,endCondition:'duration',defense:{collisionMultiplier:1,knockbackMultiplier:1},formName:'เมาไร้เงา',rebound:{strength:360,delayTicks:6,radius:72,maxHitsPerTarget:2}},
    ultimate:{maxCharge:4,rules:[{trigger:'basic-cast',amount:1,intervalTicks:1}],windupTicks:18,armedTicks:90,counterLabel:'ฤทธิ์สุรา'},ultimatePresentation:{kind:'count',label:'ฤทธิ์สุรา'}},
  {id:'chain-hook',name:'โซ่ล่ามังกร',range:4,castTicks:12,cooldownTicks:108,
    description:`เหวี่ยงตะขอทุก 1.8 วินาที ง้าง 0.2 วินาที · ตะขอพุ่งตรง โดนสร้าง ${scaledDamage(14)} HP แล้วดึงเข้าหาผู้ใช้ 0.8 วินาที · หลบได้และแท่นขวางได้ ไม่ปิดการใช้สกิล · เกี่ยวสำเร็จจึงสะสมข้อโซ่`,
    basicCharge:{name:'ตะขอ',mode:'recharge',maxStacks:1,intervalTicks:108,damagePerStack:0},
    effect:{kind:'hook',damage:14,speed:720,radius:18,lifetimeTicks:32,angles:[0],pullTicks:48,acceleration:1800,contactDamage:8,distanceBonus:16}},
  {id:'chain-dragons',name:'โซ่มังกรขย้ำวิญญาณ',range:5,castTicks:1,cooldownTicks:30,
    description:`เกี่ยวสำเร็จครบข้อโซ่ 3/3 · ง้าง 0.2 วินาทีแล้วยิงโซ่หัวมังกร ${scaledDamage(10)} HP หากโดนจะพันรอบเป้าหมายและดึงเข้าหาตัว 1.2 วินาที · บีบรัดที่ 0.4 และ 0.8 วินาที ครั้งละ ${scaledDamage(8)} HP แล้วขย้ำปิดท้าย ${scaledDamage(24)} HP · ไม่จบโซ่เมื่อชนกัน ไม่แช่แข็งหรือปิดสกิล · ยิงหลบได้ โซ่ขาดเมื่อมีแท่นขวาง ห่างเกิน 520 หรือผู้ใช้ถูกผนึกวิชา · ไม่สะสมข้อโซ่ระหว่างอัลติ`,
    effect:{kind:'hook',damage:10,speed:780,radius:25,lifetimeTicks:45,angles:[0],pullTicks:72,acceleration:1600,contactDamage:0,distanceBonus:0,constriction:{intervalTicks:24,pulseDamage:8,finisherDamage:24}},
    ultimate:{maxCharge:3,rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}],windupTicks:12,armedTicks:120,counterLabel:'ข้อโซ่'},ultimatePresentation:{kind:'count',label:'ข้อโซ่'}},
  {id:'spear-cloud',name:'หอกแหวกเมฆา',range:3,castTicks:6,cooldownTicks:126,
    description:`ง้าง 0.1 วินาทีแล้วเล็งตำแหน่งล่าสุดก่อนแทง ระยะหอก 230 คมมีผล 0.13 วินาที โดนแต่ละตัวได้ครั้งเดียว · โดนสร้าง ${scaledDamage(9)} HP ปลายหอกแรงขึ้น 40% และผลักเล็กน้อย · ฟื้นทุก 2.1 วินาที ทิศคงที่หลังแทง แนวแทงหลบได้และกำแพงขวางได้`,
    basicCharge:{name:'คมหอก',mode:'recharge',maxStacks:1,intervalTicks:126,damagePerStack:0},
    effect:{kind:'thrust',damage:9,length:230,radius:28,activeTicks:8,tipStart:.65,tipMultiplier:1.4},knockback:{strength:90}},
  {id:'spear-heaven',name:'หนึ่งหอกเปิดนภา',range:4,castTicks:1,cooldownTicks:30,
    description:`หอกปกติโดนจริงสะสมเจตหอก 3/3 · เตือน 0.2 วินาที แล้วเล็งเผื่อทิศศัตรูตอนเริ่มพุ่งก่อนแทง 0.3 วินาที สร้าง ${scaledDamage(12)} HP ต่อเป้าหมายหนึ่งครั้งด้วยคมหอกด้านหน้า 80 แล้วระเบิดปลายทางรัศมี 105 ${scaledDamage(16)} HP · ไม่เลี้ยวตามศัตรู หยุดเมื่อชนกำแพงหรือแท่น และไม่สะสมเจตหอกขณะพุ่ง`,
    effect:{kind:'thrust',damage:12,length:300,radius:24,tipStart:1,tipMultiplier:1,lunge:{speed:1000,durationTicks:18,burstDamage:16,burstRadius:105}},
    ultimate:{maxCharge:3,rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}],windupTicks:12,armedTicks:120,counterLabel:'เจตหอก'},
    ultimatePresentation:{kind:'count',label:'เจตหอก'}},
  {id:'qin-string',name:'สายพิณผ่าธารา',range:5,castTicks:9,cooldownTicks:96,
    description:`ดีดคลื่นทุก 1.6 วินาที ง้าง 0.15 วินาที · โดนสร้าง ${scaledDamage(12)} HP สะท้อนกำแพงได้ครั้งเดียว ดาเมจเหลือ 65% · หนึ่งคลื่นโดนได้หนึ่งเป้าหมายและสะสมทำนองได้หนึ่งแต้ม`,
    basicCharge:{name:'สายพิณ',mode:'recharge',maxStacks:1,intervalTicks:96,damagePerStack:0},
    effect:{kind:'projectile',damage:12,speed:460,radius:23,lifetimeTicks:180,aiming:'predictive',maxLeadSeconds:.2,reflection:{remaining:1,damageMultiplier:.65}}},
  {id:'qin-sevenfold',name:'เจ็ดสายสะท้านสวรรค์',range:5,castTicks:1,cooldownTicks:30,
    description:`โจมตีด้วยคลื่นปกติโดนจริงสะสมทำนอง 4/4 · รวมเสียง 0.3 วินาทีแล้วบรรเลง 7 จังหวะห่างกัน 0.2 วินาที สลับทิศรอบตัว · คลื่นละ ${scaledDamage(15)} HP จังหวะสุดท้ายใหญ่ขึ้นและแรงสองเท่า · หกคลื่นแรกสะท้อนกำแพงได้ครั้งเดียว ส่วนโน้ตทองชิ่งได้ 3 ครั้ง ดาเมจคงเหลือ 80% ต่อการชิ่ง อยู่ได้สูงสุด 6 วินาที ไม่สะสมทำนองระหว่างบรรเลง`,
    effect:{kind:'projectile-sequence',damage:15,speed:470,radius:23,lifetimeTicks:180,angles:[0,60,-60,120,-120,180,0],intervalTicks:12,finisherMultiplier:2,finisherRadius:32,finisherReflection:{remaining:3,damageMultiplier:.8},finisherLifetimeTicks:360,reflection:{remaining:1,damageMultiplier:.65}},
    ultimate:{maxCharge:4,rules:[{trigger:'basic-hit',amount:1,intervalTicks:1}],windupTicks:18,armedTicks:180,counterLabel:'ทำนอง'},
    ultimatePresentation:{kind:'count',label:'ทำนอง'}},
  { id:'ink-brush',name:'พู่กันแบ่งนภา',range:5,castTicks:12,cooldownTicks:150,
    description:`ตวัดหมึกขวางทางศัตรูทุก 2.5 วินาที มีจังหวะง้าง 0.2 วินาที · ตอนตวัดโดนสร้าง ${scaledDamage(12)} HP แล้วทิ้งรอย 8 วินาที · รอยเดิมไม่ทำดาเมจซ้ำ มีได้ 3 รอย`,
    basicCharge:{name:'ปลายพู่กัน',mode:'recharge',maxStacks:1,intervalTicks:150,damagePerStack:0},
    effect:{kind:'ink-stroke',damage:12,length:132,radius:12,lifetimeTicks:480,fieldStatus:INK_MEMORY.status}},
  {id:'ink-dragon',name:'วาดมังกรปลุกสวรรค์',range:5,castTicks:1,cooldownTicks:30,
    description:`รอยหมึกที่ยังอยู่ครบ 3/3 ปลุกเป็นมังกรจากทั้งสามรอย หลังเตือน 0.4 วินาที · มังกรละ ${scaledDamage(18)} HP พุ่งตรงไปยังจุดที่เล็งไว้ตอนเริ่มท่า ไม่เลี้ยวตามและชนกำแพงหรือแท่นได้ · ใช้รอยหมึกทั้งหมด`,
    effect:{kind:'ink-dragons',damage:18,speed:530,radius:19,lifetimeTicks:100},
    ultimate:{resource:'ink-strokes',maxCharge:3,rules:[],windupTicks:24,armedTicks:120,counterLabel:'รอยหมึก'},
    ultimatePresentation:{kind:'count',label:'รอยหมึก'}},
  { id: 'mirror-double', name: 'บุปผาในกระจก', range: 5, castTicks: 9, cooldownTicks: 120,
    description: 'สร้างร่างลวง 1 ร่างทางฝั่งศัตรู อยู่ 3 วินาที · สลับตำแหน่งหลัง 0.3 วินาทีหากจุดหมายว่าง · ร่างลวงไม่ทำดาเมจและแตกเมื่อศัตรูชนหรือโจมตี · ฟื้นหนึ่งครั้งทุก 2 วินาที มีร่างลวงได้ครั้งละหนึ่งร่าง',
    basicCharge: { name: 'เงากระจก', mode: 'recharge', maxStacks: 1, intervalTicks: 120, damagePerStack: 0 },
    effect: { kind: 'decoy', damage: 0, lifetimeTicks: 180, swapDelayTicks: 18, distance: 100 } },
  { id: 'mirror-moonfall', name: 'พันกระจกคืนจันทรา', range: 5, castTicks: 1, cooldownTicks: 30,
    description: `ร่างลวงถูกโจมตีแตกสะสมเศษกระจก 2/2 · กระจกสามบานเล็งดักทางศัตรูเล็กน้อย เตือน 0.5 วินาทีแล้วรวมคมแสงสร้าง ${scaledDamage(60)} HP · ล็อกจุดตอนปล่อย ไม่ติดตามเป้าหมาย หนีออกจากเขตได้`,
    effect: { kind: 'zone', damage: 60, radius: 132, delayTicks: 30, aimLeadSeconds: .25 },
    ultimate: { maxCharge: 2, windupTicks: 1, armedTicks: 120, counterLabel: 'เศษกระจก', rules: [{ trigger: 'passive-proc', amount: 1, intervalTicks: 1 }] },
    ultimatePresentation: { kind: 'count', label: 'เศษกระจก' } },
  { id: 'frost-flower', name: 'บุปผาเหมันต์', range: 5, castTicks: 12, cooldownTicks: 60,
    description: `ดอกผลึก 0/2 ฟื้นทีละดอกทุก 1.8 วินาที · วางดอกน้ำแข็งบนเส้นทางศัตรู เตือน 0.5 วินาทีก่อนทำงาน อยู่ต่อ 2.5 วินาที · ผู้แตะดอกหลังพร้อมรับ ${scaledDamage(12)} HP และแช่แข็ง 0.45 วินาที หยุดเคลื่อนที่และใช้วิชา · หลังหายกันแช่แข็งซ้ำ 2 วินาที · หลบได้ ไม่ไล่ตาม`,
    basicCharge: { name: 'ดอกผลึก', mode: 'recharge', maxStacks: 2, intervalTicks: 108, damagePerStack: 0 },
    effect: { kind: 'zone', damage: 12, radius: 85, delayTicks: 30, aimLeadSeconds: .1, triggerWindowTicks: 150 },
    onHitStatus: { id: 'frost-freeze', name: 'แช่แข็ง', durationTicks: 27, stacking: 'refresh', effect: { kind: 'freeze', immunityTicks: 120 }, vfxClipId: 'frost-aura', vfxColor: '#a8d9ff' } },
  { id: 'frost-palace', name: 'วังวนเหมันต์ผนึกฟ้า', range: 5, castTicks: 1, cooldownTicks: 30,
    description: `สะสมพลังเหมันต์ 12 ต่อวินาที และ 12 เมื่อดอกน้ำแข็งโจมตีโดนจริง · ครบ 100 สร้างวังวนเหมันต์ตรงจุดที่ร่าย 2 วินาที ลดความเร็วศัตรูในเขต 25% ก่อนระเบิด ${scaledDamage(40)} HP และแช่แข็ง 0.7 วินาที · หลังหายกันแช่แข็งซ้ำ 2 วินาที · หนีออกจากเขตเพื่อหลบระเบิดได้`,
    effect: { kind: 'zone', damage: 40, radius: 210, delayTicks: 120, aimLeadSeconds: 0, placement: 'caster',
      fieldStatus: { id: 'frost-domain', name: 'เขตเหมันต์', durationTicks: 2, stacking: 'refresh', effect: { kind: 'speed-modifier', reductionPerStack: .25, group: 'frost' }, vfxColor: '#a8d9ff' } },
    ultimate: { maxCharge: 100, windupTicks: 1, armedTicks: 120, rules: [{ trigger: 'time', amount: 12, intervalTicks: 60 }, { trigger: 'basic-hit', amount: 12, intervalTicks: 1 }] },
    ultimatePresentation: { kind: 'energy', label: 'พลังเหมันต์' },
    onHitStatus: { id: 'frost-freeze', name: 'แช่แข็ง', durationTicks: 42, stacking: 'refresh', effect: { kind: 'freeze', immunityTicks: 120 }, vfxClipId: 'frost-aura', vfxColor: '#a8d9ff' } },
  { id: 'blood-petal', name: 'กลีบบัวกรีดวิญญาณ', range: 0, castTicks: 0, cooldownTicks: 90,
    description: `กลีบโลหิต 0/1 ฟื้นทุก 1.5 วินาที · ชนจริงจึงฟัน ${scaledDamage(18)} HP · เมื่อฟันเกิดดาเมจจ่าย 2% HP สูงสุดแล้วดูดเลือดคืน · ค่าร่ายไม่ทำให้ HP ต่ำกว่า 1 และไม่ชาร์จอัลติ`,
    effect: { kind: 'melee', damage: 18 }, healthCostOnHit: .02,
    basicCharge: { name: 'กลีบโลหิต', mode: 'recharge', maxStacks: 1, intervalTicks: 90, damagePerStack: 0 } },
  { id: 'blood-lotus', name: 'บัวโลหิตผลาญสวรรค์', range: 0, castTicks: 0, cooldownTicks: 30,
    description: `รับดาเมจจริงจากศัตรู 1 HP ได้ 3.5 พลังโลหิต · ครบ 100 แปรเป็นร่างบัวโลหิต 5 วินาที ความเร็ว +12% · ชนศัตรูปล่อยกลีบฟัน ${scaledDamage(24)} HP เพิ่มจากดาเมจปะทะ เว้นทุก 0.9 วินาที · ดูดเลือดเพิ่ม 25% และหยุดใช้สกิลปกติระหว่างร่าง · ไม่สะสมพลังระหว่างอัลติ`,
    effect: { kind: 'impact-form', damage: 24, speedMultiplier: 1.12, durationTicks: 300, hits: 3, pairCooldownTicks: 54, strikeCooldownTicks: 54, endCondition: 'duration', lifestealBonus: .25, formName: 'ร่างบัวโลหิต' },
    ultimate: { maxCharge: 100, windupTicks: 1, armedTicks: 1, rules: [{ trigger: 'enemy-damage', amount: 3.5, intervalTicks: 1 }] },
    ultimatePresentation: { kind: 'energy', label: 'พลังโลหิต' } },
  {id:'poison-needles',name:'เข็มจันทร์อาบพิษ',range:5,castTicks:10,cooldownTicks:90,
    description:`ยิงเข็ม 3 เล่มเป็นพัดแคบทุก 1.5 วินาที · กระสุนบินตรง หลบได้และติดแท่น · เป้าหมายหนึ่งรับดาเมจ ${scaledDamage(6)} HP และพิษเพิ่มได้เพียง 1 ชั้นต่อชุด`,
    effect:{kind:'projectile',damage:6,speed:520,radius:7,lifetimeTicks:90,aiming:'predictive',maxLeadSeconds:.16,volley:{count:3,spreadDegrees:24}},
    basicCharge:{name:'เข็มจันทรา',mode:'recharge',maxStacks:1,intervalTicks:90,damagePerStack:0}},
  {id:'poison-eclipse',name:'จันทราพิษดับชีพ',range:5,castTicks:1,cooldownTicks:30,effect:{kind:'status-burst',damage:38},
    description:`พิษบนศัตรูตัวเดียวครบ 4 ชั้น ประกาศท่าไม้ตายแล้วระเบิดใส่ตัวนั้น ${scaledDamage(38)} HP · ล้างเฉพาะพิษของตนบนเป้าหมาย เริ่มสะสมใหม่ · ไม่รวมพิษจากคนอื่นหรือหลายเป้าหมาย`,
    ultimate:{resource:'status-stacks',statusId:'moon-poison',maxCharge:4,rules:[],windupTicks:1,armedTicks:120,counterLabel:'พิษจันทรา'},
    ultimatePresentation:{kind:'count',label:'พิษจันทรา',statusCounter:{statusId:'moon-poison',maximum:4}}},
  { id: 'pulse-strike', name: 'ฝ่ามือสะท้านฟ้า', shortName: 'ฝ่ามือ', range: 0, castTicks: 0, cooldownTicks: 90, effect: { kind: 'melee', damage: 14 }, basicCharge: { name: 'ปราณ', maxStacks: 5, intervalTicks: 60, damagePerStack: .1 } },
  { id: 'spark-shot', name: 'ดัชนีทะลวงเมฆ', shortName: 'ดัชนี', range: 5, castTicks: 12, cooldownTicks: 105,
    description: 'เล็งเผื่อช่วงสั้นตอนปล่อยกระสุน · ยิงทุก 1.75 วินาที · ปราณ +1 ทุกวินาที สูงสุด 5 เพิ่มดาเมจแต้มละ 10% · ใช้แต้มเมื่อเริ่มร่าย',
    effect: { kind: 'projectile', damage: 10, speed: 500, radius: 9, lifetimeTicks: 90, aiming: 'predictive', maxLeadSeconds: .3 }, basicCharge: { name: 'ปราณ', maxStacks: 5, intervalTicks: 60, damagePerStack: .1 } },
  { id: 'solar-palm', name: 'ฝ่ามือสะท้านฟ้า', range: 0, castTicks: 0, cooldownTicks: 90, effect: { kind: 'melee', damage: 14 },
    basicCharge: { name: 'ประกายเพลิง', mode: 'power', maxStacks: 5, intervalTicks: 60, damagePerStack: .1 },
    description: 'ประกายเพลิง +1 ทุกวินาที สูงสุด 5 · แต่ละแต้มเพิ่มดาเมจ 10% · ชนจริงจึงออกฝ่ามือและใช้แต้มทั้งหมด' },
  { id: 'solar-heavenfall', name: 'สุริยันถล่มสวรรค์', range: 0, castTicks: 0, cooldownTicks: 30, effect: { kind: 'melee', damage: 30 },
    ultimatePresentation: { kind: 'energy' },
    description: `ชนกำแพง +20 · ชนคู่ต่อสู้ +30 · ครบ 100 ประกาศท่าไม้ตาย แล้วรวมปราณ 0.6 วินาที · จำเป้าหมายที่ชนระหว่างเริ่มท่าไว้เพื่อปล่อย ${scaledDamage(30)} HP เมื่อพร้อม หากยังไม่ชนจะรอปะทะภายใน 6 วินาที`,
    ultimate: { maxCharge: 100, windupTicks: 36, armedTicks: 360,
      rules: [{ trigger: 'wall-impact', amount: 20, intervalTicks: 18 }, { trigger: 'character-impact', amount: 30, intervalTicks: 18 }] } },
  { id: 'jade-needle', name: 'ดัชนีธาราหยก', range: 5, castTicks: 12, cooldownTicks: 105,
    description: 'ดัชนีธาราหยกเก็บได้ 1 ชาร์จ · ฟื้นหนึ่งชาร์จทุก 1.75 วินาที · ใช้เมื่อเริ่มร่ายและเล็งเผื่อช่วงสั้นตอนปล่อยกระสุน · โจมตีโดนสะสมท่าไม้ตาย 1 ครั้ง',
    effect: { kind: 'projectile', damage: 11, speed: 500, radius: 9, lifetimeTicks: 90, aiming: 'predictive', maxLeadSeconds: .3 },
    basicCharge: { name: 'หยดปราณ', mode: 'recharge', maxStacks: 1, intervalTicks: 105, damagePerStack: 0 } },
  { id: 'jade-nine-streams', name: 'เก้าธาราหวนสมุทร', range: 5, castTicks: 1, cooldownTicks: 1,
    description: `ดัชนีธาราหยกโจมตีโดนจริง 3 ครั้งจึงพร้อม · ประกาศท่าไม้ตายแล้วรวมปราณ 0.6 วินาที · คลื่นน้ำหมุนวนพร้อมขยายรอบจุดปล่อยถึงรัศมี 320 ใน 1.2 วินาที ทำดาเมจ ${scaledDamage(22)} HP ต่อเป้าหมายเพียงครั้งเดียว พร้อมเปียกชื้น`,
    effect: { kind: 'area', damage: 22, radius: 320, durationTicks: 72 },
    ultimate: { maxCharge: 3, windupTicks: 36, armedTicks: 120, rules: [{ trigger: 'basic-hit', amount: 1, intervalTicks: 1 }] } },
  { id: 'astral-snare', name: 'ดาราตรึงนภา', range: 5, castTicks: 1, cooldownTicks: 114,
    description: 'เก็บได้ 1 ชาร์จ ฟื้นทุก 1.9 วินาที · วางเขตดารารอบเป้าหมายรัศมี 108 ล็อกตำแหน่งแล้วเตือน 0.5 วินาทีก่อนระเบิด ศัตรูออกจากเขตได้ · โดนจริงจึงฝากตราดารา',
    effect: { kind: 'zone', damage: 14, radius: 108, delayTicks: 30, aimLeadSeconds: .08, placementOrbitRadius: 40 },
    basicCharge: { name: 'ดารา', mode: 'recharge', maxStacks: 1, intervalTicks: 114, damagePerStack: 0 } },
  { id: 'astral-prison', name: 'ค่ายกลดาราผนึกฟ้า', range: 5, castTicks: 1, cooldownTicks: 1,
    ultimatePresentation: { kind: 'count', label: 'ตราดารา', statusCounter: { statusId: 'astral-mark', maximum: 3 } },
    description: `สลายตราดารา 1 ชุด (3 ตราบนเป้าหมายเดียวกัน) จึงพร้อม · ประกาศท่าแล้วรวมปราณ 0.6 วินาที · วางค่ายกลรัศมี 210 ดึงศัตรู 1.5 วินาที ก่อนระเบิด ${scaledDamage(30)} HP ต่อเป้าหมายที่ยังอยู่ในเขต · แรงดึงไม่ย้ายตัวละครทันที`,
    effect: { kind: 'zone', damage: 30, radius: 210, delayTicks: 90, aimLeadSeconds: 0, pullAcceleration: 720 },
    ultimate: { maxCharge: 1, windupTicks: 36, armedTicks: 120, rules: [{ trigger: 'passive-proc', amount: 1, intervalTicks: 1 }] } },
  { id: 'blossom-call', name: 'ฝากวิญญาณบุปผา', range: 5, castTicks: 12, cooldownTicks: 90,
    description: 'ส่งภูตไปเกาะศัตรูใกล้สุดโดยไม่ทำดาเมจ · ฟื้น 1 ชาร์จทุก 1.5 วินาที มีได้สูงสุด 3 ตนรวมภูตที่กำลังเดินทาง · นับเฉพาะภูตที่เกาะแล้วและยังมีชีวิต',
    effect: { kind: 'summon', damage: 0, summon: BLOSSOM_SPIRIT },
    basicCharge: { name: 'เมล็ดบุปผา', mode: 'recharge', maxStacks: 1, intervalTicks: 90, damagePerStack: 0 } },
  { id: 'blossom-myriad', name: 'บุปผาหมื่นวิญญาณ', range: 5, castTicks: 1, cooldownTicks: 1,
    description: `ภูตของผู้ใช้เกาะศัตรูและยังมีชีวิตครบ 3 ตน เริ่มประกาศอัลติทันทีแล้วใช้ภูตทั้งสามระเบิด · ดาเมจรวม ${scaledDamage(48)} HP แบ่ง ${scaledDamage(16)} HP ต่อภูตที่เกาะแต่ละเป้าหมาย · ไม่ต้องชาร์จตามเวลา`,
    effect: { kind: 'summon', damage: 48, summon: BLOSSOM_SPIRIT, detonation: true },
    ultimate: { resource: 'attached-summons', maxCharge: 3, windupTicks: 1, armedTicks: 120, rules: [] } },
  { id: 'shadow-cut', name: 'กระบี่ตัดเงา', range: 0, castTicks: 0, cooldownTicks: 90,
    description: `ฟื้นคมกระบี่ 1 ชาร์จทุก 1.5 วินาที · ปะทะจริงจึงฟัน ${scaledDamage(28)} HP และพุ่งผ่านเป้าหมาย · กำแพง สิ่งกีดขวาง และตัวละครอื่นหยุดท่าพุ่งได้ · โจมตีโดนเพิ่มเจตกระบี่ 1 แต้ม`,
    effect: { kind: 'dash', damage: 28, speed: 1050, durationTicks: 18 },
    basicCharge: { name: 'คมกระบี่', mode: 'recharge', maxStacks: 1, intervalTicks: 90, damagePerStack: 0 } },
  { id: 'shadow-myriad', name: 'หนึ่งกระบี่หมื่นเงา', range: 0, castTicks: 0, cooldownTicks: 60,
    description: `กระบี่ตัดเงาโจมตีโดนจริงครบ 3 ครั้ง สะสมเจตกระบี่เต็ม · รอปะทะครั้งใหม่จึงประกาศท่า · ฟันรัว 6 ครั้ง ตามด้วยฟันหนัก 1 ครั้งในพื้นที่รัศมี 180 ที่ล็อกตอนปล่อย · รวมสูงสุด ${scaledDamage(60)} HP ต่อเป้าหมายที่โดนครบ ศัตรูออกจากเขตเพื่อหลบบางจังหวะได้`,
    effect: { kind: 'flurry', damage: 60, radius: 180, hits: 7, intervalTicks: 8, delayTicks: 6, finisherWeight: 2.4 },
    ultimate: { counterLabel: 'เจตกระบี่', activation: 'impact', maxCharge: 3, windupTicks: 1, armedTicks: 120, rules: [{ trigger: 'basic-hit', amount: 1, intervalTicks: 1 }] } },
  { id: 'mountain-palm', name: 'ฝ่ามือสะเทือนขุนเขา', range: 0, castTicks: 0, cooldownTicks: 90,
    description: `ปะทะจริงจึงออกฝ่ามือ ${scaledDamage(18)} HP และผลักศัตรู · หากศัตรูชนกำแพงภายใน 1.5 วินาที เพิ่ม ${scaledDamage(14)} HP และแรงสะท้อน 1 ครั้ง · นับครั้งเดียวต่อการผลัก หากชนตัวละครหรือแท่นก่อนจะยกเลิกแต้ม`,
    effect: {kind:'melee', damage:18}, knockback: {strength:720, wallSlam:{damage:14,windowTicks:90}},
    basicCharge: {name:'ปราณศิลา',mode:'recharge',maxStacks:1,intervalTicks:90,damagePerStack:0} },
  { id: 'mountain-heavenfall', name: 'มหาภูผาทลายสวรรค์', range: 0, castTicks: 0, cooldownTicks: 30,
    description: `ผลักด้วยฝ่ามือแล้วศัตรูชนกำแพงสำเร็จ 3 ครั้ง · รอปะทะครั้งใหม่เพื่อประกาศอัลติและรวมปราณ 0.3 วินาที · คลื่นศิลาแผ่ออกจากจุดปล่อยรัศมี 230 ใน 0.8 วินาที ทำ ${scaledDamage(50)} HP และผลักเป้าหมายที่โดนครั้งเดียว · อัลติไม่สะสมแรงสะท้อนเอง`,
    effect: {kind:'area',damage:50,radius:230,durationTicks:48}, knockback:{strength:720},
    ultimate: {counterLabel:'แรงสะท้อน',activation:'impact',maxCharge:3,windupTicks:18,armedTicks:120,rules:[{trigger:'wall-slam',amount:1,intervalTicks:1}]},
    ultimatePresentation: {kind:'count',label:'แรงสะท้อน'} },
  {id:'lightning-strike',name:'อัสนีพุ่งสะบั้น',range:0,castTicks:0,cooldownTicks:90,
    description:`ชนจริงจึงใช้กระแสอัสนีทั้งหมด · ทำ ${scaledDamage(16)}–${scaledDamage(28)} HP ตามขั้นสะสม · โจมตีโดนแล้วเร่งความเร็ว 40% และค่อยลดลงใน 0.6 วินาที · ไม่มีดาเมจพุ่งซ้ำ`,
    effect:{kind:'melee',damage:16},basicCharge:{name:'กระแสอัสนี',mode:'distance',maxStacks:3,intervalTicks:1,distancePerStack:160,speedPerStack:.08,damagePerStack:.25,afterHitBoost:{multiplier:1.4,durationTicks:36},defense:{collisionMultiplier:.9,knockbackMultiplier:.15,wallSlamMultiplier:.35}}},
  {id:'lightning-ninefold',name:'อัสนีเก้าทิศ',range:0,castTicks:0,cooldownTicks:60,
    description:`โจมตีปกติด้วยกระแสเต็มและโดนจริง สะสมตราอัสนี 1/3 · ครบแล้วแปรกาย 4 วินาที ความเร็ว +100% พร้อมต้านแรงผลัก 85% ลดดาเมจชน 10% และลดดาเมจแรงสะท้อนจากการถูกผลักชนกำแพง 65% · ชนหรือวิ่งเฉียดขอบตัวศัตรูในระยะ 18 WU ปล่อยสายฟ้า ${scaledDamage(16)} HP เว้นทุกการโจมตี 1.25 วินาที · ครบเวลาจึงคืนร่าง ไม่จบตามจำนวนครั้ง · ไม่ทะลุแท่น ไม่ล็อกเป้า และหยุดสะสมระหว่างอัลติ`,
    effect:{kind:'impact-form',damage:16,speedMultiplier:2,durationTicks:240,hits:3,pairCooldownTicks:75,endCondition:'duration',strikeCooldownTicks:75,strikeRange:1,defense:{collisionMultiplier:.9,knockbackMultiplier:.15,wallSlamMultiplier:.35}},
    ultimate:{maxCharge:3,windupTicks:1,armedTicks:1,counterLabel:'ตราอัสนี',rules:[{trigger:'charged-basic-hit',amount:1,intervalTicks:1}]},
    ultimatePresentation:{kind:'count',label:'ตราอัสนี'}},
];
